server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/authdb
    username: root
    password: root
  sql:
    init:
      platform: mysql
      mode: always

jwt:
  secret: myVerySecureJwtKeyThatYouMustChange
  expiration: 900000
