services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Importante: configurar ambos listeners (dentro y fuera del contenedor)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Puerto externo 3307 para evitar conflicto con MySQL local
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: inventorydb
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      R2DBC_URL: r2dbc:mysql://mysql:3306/orderdb
      DB_USERNAME: root
      DB_PASSWORD: root
      INVENTORY_DOMAIN: http://inventory-service:8082
      RETRY_MAX_ATTEMPTS: 3
      RETRY_DELAY_MS: 1000

  store-service:
    build:
      context: ./store-service
    depends_on:
      - inventory-service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: storedb_a
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ORDER_SERVICE_URL: http://order-service:8083
      LOGGING_LEVEL_ROOT: INFO

volumes:
  mysql_data:
  kafka_data:
